/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui2;

import java.util.List;
import javax.swing.JOptionPane;
import jpa.AltaJpaController;
import jpa.CIDJpaController;
import jpa.InternacaoJpaController;
import jpa.LeitoJpaController;
import jpa.LocalizacaoJpaController;
import jpa.ProfissionalJpaController;
import jpa.MotivoAltaJpaController;
import jpa.PacienteJpaController;
import jpa.ProcedimentoJpaController;
import jpa.exceptions.NonexistentEntityException;
import model.Alta;
import model.CID;
import model.Internacao;
import model.Leito;
import model.Localizacao;
import model.Profissional;
import model.MotivoAlta;
import model.Paciente;
import model.Procedimento;

/**
 *
 * @author Ciça
 */
public class guiAlta extends javax.swing.JInternalFrame {

    Internacao inter;
    Paciente paciente;
    Alta alta;
    private String s;


    /**
     * Creates new form guiAlta
     */
    public guiAlta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPront = new javax.swing.JTextField();
        btnBuscarPaciente = new javax.swing.JButton();
        dataInicio1 = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaeInt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboMedicoInt = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        cboProcedInt = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txtDescProcedInt = new javax.swing.JTextField();
        cboCID = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        txtDescricaoCIDInt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cboLocal = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cboLeito = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        cboCIDAlta = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cboMedicoAlta = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        cboProcedAlta = new javax.swing.JComboBox();
        horaAlta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cboMotivoAlta = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        dataAlta = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtDescricaoCIDAlta = new javax.swing.JTextField();
        txtDescProcedAlta = new javax.swing.JTextField();
        bntEditar1 = new javax.swing.JButton();
        bntCancelar1 = new javax.swing.JButton();
        bntExcluir1 = new javax.swing.JButton();
        bntGravar1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Efetuar Alta");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Prontuário:");

        txtPront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProntActionPerformed(evt);
            }
        });

        btnBuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Pesquisa.jpg"))); // NOI18N
        btnBuscarPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteActionPerformed(evt);
            }
        });

        dataInicio1.setEnabled(false);

        jLabel17.setText("Hora:");

        txtHora.setEditable(false);

        jLabel20.setText("Data:");

        txtNome.setEditable(false);

        jLabel15.setText("Nome:");

        jLabel2.setText("CPF:");

        txtCPF.setEditable(false);
        txtCPF.setEnabled(false);

        jLabel5.setText("Telefone:");

        txtTelefone.setEditable(false);
        txtTelefone.setEnabled(false);

        jLabel4.setText("Data de Nascimento:");

        txtDataNasc.setEditable(false);
        txtDataNasc.setEnabled(false);

        jLabel3.setText("Mãe:");

        txtMaeInt.setEditable(false);
        txtMaeInt.setEnabled(false);

        jLabel7.setText("Médico:");

        cboMedicoInt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMedicoIntItemStateChanged(evt);
            }
        });

        jLabel18.setText("Procedimento:");

        cboProcedInt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboProcedIntItemStateChanged(evt);
            }
        });
        cboProcedInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboProcedIntActionPerformed(evt);
            }
        });

        jLabel10.setText("Descrição:");

        txtDescProcedInt.setEditable(false);
        txtDescProcedInt.setEnabled(false);
        txtDescProcedInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescProcedIntActionPerformed(evt);
            }
        });

        cboCID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCIDItemStateChanged(evt);
            }
        });
        cboCID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCIDActionPerformed(evt);
            }
        });

        jLabel19.setText("CID:");

        txtDescricaoCIDInt.setEditable(false);
        txtDescricaoCIDInt.setEnabled(false);

        jLabel21.setText("Local:");

        cboLocal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLocalItemStateChanged(evt);
            }
        });

        jLabel6.setText("Leito:");

        cboLeito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLeitoItemStateChanged(evt);
            }
        });

        jLabel25.setText("CID:");

        cboCIDAlta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCIDAltaItemStateChanged(evt);
            }
        });

        jLabel11.setText("Médico:");

        cboMedicoAlta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMedicoAltaItemStateChanged(evt);
            }
        });

        jLabel27.setText("Procedimento:");

        cboProcedAlta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboProcedAltaItemStateChanged(evt);
            }
        });

        jLabel9.setText("Motivo da Alta:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("ALTA DA INTERNAÇÃO");

        jLabel23.setText("Data:");

        jLabel24.setText("Hora:");

        jLabel12.setText("Descrição:");

        jLabel26.setText("Descriçao:");

        txtDescricaoCIDAlta.setEditable(false);
        txtDescricaoCIDAlta.setEnabled(false);

        txtDescProcedAlta.setEditable(false);
        txtDescProcedAlta.setEnabled(false);
        txtDescProcedAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescProcedAltaActionPerformed(evt);
            }
        });

        bntEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Editar.jpg"))); // NOI18N
        bntEditar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntEditar1.setMaximumSize(new java.awt.Dimension(59, 63));
        bntEditar1.setMinimumSize(new java.awt.Dimension(59, 63));
        bntEditar1.setPreferredSize(new java.awt.Dimension(68, 68));
        bntEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditar1ActionPerformed(evt);
            }
        });

        bntCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Cancelar.jpg"))); // NOI18N
        bntCancelar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntCancelar1.setPreferredSize(new java.awt.Dimension(68, 68));
        bntCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelar1ActionPerformed(evt);
            }
        });

        bntExcluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Excluir.jpg"))); // NOI18N
        bntExcluir1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntExcluir1.setPreferredSize(new java.awt.Dimension(68, 68));
        bntExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluir1ActionPerformed(evt);
            }
        });

        bntGravar1.setForeground(new java.awt.Color(153, 153, 153));
        bntGravar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Gravar.jpg"))); // NOI18N
        bntGravar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntGravar1.setPreferredSize(new java.awt.Dimension(68, 68));
        bntGravar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGravar1ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel13.setText("Tipo de Leito:");

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cirúrgico", "Clínico", "Pediátrico", "Obstétrico" }));

        jLabel14.setText("Descrição:");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("INTERNAÇÃO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(30, 30, 30)
                            .addComponent(txtMaeInt))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboMedicoInt, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19)
                                .addComponent(jLabel13))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cboLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cboLeito, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cboProcedInt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel10))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cboCID, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel14)))
                                    .addGap(11, 11, 11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDescProcedInt)
                                        .addComponent(txtDescricaoCIDInt))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPront)
                                .addGap(14, 14, 14)
                                .addComponent(btnBuscarPaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel16)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(22, 22, 22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(dataAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(horaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cboMotivoAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMedicoAlta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboProcedAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboCIDAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(11, 11, 11)
                                .addComponent(txtDescProcedAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDescricaoCIDAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(bntGravar1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(bntEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(bntCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(bntExcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(511, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(486, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(horaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(dataAlta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(cboMotivoAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboMedicoAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(cboProcedAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboCIDAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtDescProcedAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(txtDescricaoCIDAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntGravar1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntExcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarPaciente)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPront, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dataInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaeInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cboMedicoInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cboProcedInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtDescProcedInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel14)
                            .addComponent(txtDescricaoCIDInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboLeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel21)))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProntActionPerformed

    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed
        // TODO add your handling code here:
        
        try {
            paciente = new PacienteJpaController().getPaciente(txtPront.getText());
            List l = new InternacaoJpaController().getInternacao(paciente);
            inter = new InternacaoJpaController().getInterPaciente(txtPront.getText());
            
//            if(!(l.isEmpty())){
//                
//                txtPront.setText(inter.getProntuario().toString());
//                txtNome.setText(inter.getNome().toString());
//                txtCPF.setText(inter.getCpf().toString());
//                txtDataNasc.setText(inter.getDataNasc().toString());
//                txtTelefone.setText(inter.getTelefone().toString());
//                txtMaeInt.setText(inter.getMae().toString());
//                txtHora.setText(inter.getHora().toString());
//                dataInicio1.setCalendar(inter.getDataEntrada());
//                
//                cboMedicoInt.setSelectedItem(inter.getMedico());
//                cboCID.setSelectedItem(inter.getCid());
//                cboProcedInt.setSelectedItem(inter.getProced());
//                cboLeito.setSelectedItem(inter.getLeito());
//                cboLocal.setSelectedItem(inter.getLocal());
//            }
                txtPront.setText(inter.getProntuario().toString());
                txtNome.setText(inter.getNome().toString());
                txtCPF.setText(inter.getCpf().toString());
                txtDataNasc.setText(inter.getDataNasc().toString());
                txtTelefone.setText(inter.getTelefone().toString());
                txtMaeInt.setText(inter.getMae().toString());
                txtHora.setText(inter.getHora().toString());
                dataInicio1.setCalendar(inter.getDataEntrada());
                
                cboMedicoInt.setSelectedItem(inter.getMedico());
                cboCID.setSelectedItem(inter.getCid());
                cboProcedInt.setSelectedItem(inter.getProced());
                cboLeito.setSelectedItem(inter.getLeito());
                cboLocal.setSelectedItem(inter.getLocal());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Paciente com este número de prontuário não encontrado");
            txtNome.setText("");
            txtCPF.setText("");
            txtDataNasc.setText("");
            txtMaeInt.setText("");
            txtTelefone.setText("");
            txtHora.setText("");
            txtPront.setText("");
            dataInicio1.setDate(null);
            cboLeito.setSelectedIndex(0);
            cboProcedInt.setSelectedIndex(0);
            cboMedicoInt.setSelectedIndex(0);
            
            cboLocal.setSelectedIndex(0);
            cboLeito.setSelectedIndex(0);
            cboCID.setSelectedIndex(0);
            return;
        }

//        txtPront.setText(paciente.getId().toString());
//        txtNome.setText(paciente.getNome().toString());
//        txtCPF.setText(paciente.getCpf().toString());
//        txtDataNasc.setText(paciente.getDataNasc().toString());
//        txtMaeInt.setText(paciente.getMae().toString());
//        txtTelefone.setText(paciente.getTelefone().toString());
        
        
    }//GEN-LAST:event_btnBuscarPacienteActionPerformed

    private void cboMedicoIntItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMedicoIntItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicoIntItemStateChanged

    private void cboProcedIntItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboProcedIntItemStateChanged
        // TODO add your handling code here:
        Procedimento p = (Procedimento) cboProcedInt.getSelectedItem();

        if(p==null) return;
        txtDescProcedInt.setText(p.getDescricao().toString());
        
    }//GEN-LAST:event_cboProcedIntItemStateChanged

    private void txtDescProcedIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescProcedIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescProcedIntActionPerformed

    private void cboCIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCIDItemStateChanged
        // TODO add your handling code here:

        CID c = (CID) cboCID.getSelectedItem();

        if(c==null) return;
        txtDescricaoCIDInt.setText(c.getDescricao().toString());
    }//GEN-LAST:event_cboCIDItemStateChanged

    private void cboProcedIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProcedIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboProcedIntActionPerformed

    private void cboCIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCIDActionPerformed

    private void cboLocalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLocalItemStateChanged
        // TODO add your handling code here:

        Localizacao e = (Localizacao) cboLocal.getSelectedItem();
        String s = (String) cboTipo.getSelectedItem();

        if(e==null) return;

        List l = new LeitoJpaController().getLeitoLocal(e,s);
        cboLeito.removeAllItems();
        for (int i = 0; i < l.size(); i++) {
            Leito ti = (Leito)l.get(i);
            cboLeito.addItem(ti);
        }

//                List list = new TipoLeitoJpaController().getListTipo(e);
//                cboTipo.removeAllItems();
//                for (int i = 0; i < list.size(); i++) {
//                    TipoLeito ti = (TipoLeito)list.get(i);
//                        cboTipo.addItem(ti);
//                    }
    }//GEN-LAST:event_cboLocalItemStateChanged

    private void cboLeitoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLeitoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLeitoItemStateChanged

    private void cboCIDAltaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCIDAltaItemStateChanged
        // TODO add your handling code here:
        CID c = (CID) cboCIDAlta.getSelectedItem();

        if(c==null) return;
        txtDescricaoCIDAlta.setText(c.getDescricao().toString());
    }//GEN-LAST:event_cboCIDAltaItemStateChanged

    private void cboMedicoAltaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMedicoAltaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicoAltaItemStateChanged

    private void cboProcedAltaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboProcedAltaItemStateChanged
        // TODO add your handling code here:
        Procedimento p = (Procedimento) cboProcedAlta.getSelectedItem();

        if(p==null) return;
        txtDescProcedAlta.setText(p.getDescricao().toString());
        
    }//GEN-LAST:event_cboProcedAltaItemStateChanged

    private void txtDescProcedAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescProcedAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescProcedAltaActionPerformed

    private void bntEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditar1ActionPerformed
        // TODO add your handling code here:

        if (alta==null) return;    
        
        alta.setMedico((Profissional)cboMedicoAlta.getSelectedItem());
        alta.setHora(horaAlta.getText());
        alta.setMotivo((MotivoAlta)cboMotivoAlta.getSelectedItem());
        alta.setProcedimento((Procedimento)cboProcedAlta.getSelectedItem());
        alta.setCid((CID)cboCIDAlta.getSelectedItem());        
        alta.setDataAlta(dataAlta.getCalendar());
        alta.setPaciente(paciente);
        
        alta.setLocal((Localizacao)cboLocal.getSelectedItem());
        alta.setLeito((Leito)cboLeito.getSelectedItem());

        try {
            new AltaJpaController().edit(alta);

        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "Alta não existe");
            txtPront.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Procure o Administrador do Sistema");
        }

        JOptionPane.showMessageDialog(null,"Detalhes de Alta Alterados");
        
        txtPront.setText("");
        txtNome.setText("");
        txtCPF.setText("");
        txtDataNasc.setText("");
        txtMaeInt.setText("");
        txtTelefone.setText("");
        txtHora.setText("");
        dataInicio1.setDate(null);
        cboProcedInt.setSelectedIndex(0);
        cboMedicoInt.setSelectedIndex(0);
        cboLeito.setSelectedIndex(0);
        cboCID.setSelectedIndex(0);
        cboLocal.setSelectedIndex(0);                
        
        dataAlta.setDate(null);
        horaAlta.setText("");
        cboProcedAlta.setSelectedIndex(0);
        cboMedicoAlta.setSelectedIndex(0);
        cboMotivoAlta.setSelectedIndex(0);
        cboCIDAlta.setSelectedIndex(0);

    }//GEN-LAST:event_bntEditar1ActionPerformed

    private void bntCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelar1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bntCancelar1ActionPerformed

    private void bntExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluir1ActionPerformed
        // TODO add your handling code here:
        try {
            new InternacaoJpaController().destroy(inter.getId());
        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "Internação não existe");

        }

       JOptionPane.showMessageDialog(null,"Internação de cód. "+ inter.getId()+ " excluída");

        txtPront.setText("");
        txtNome.setText("");
        txtCPF.setText("");
        txtDataNasc.setText("");
        txtMaeInt.setText("");
        txtTelefone.setText("");
        txtHora.setText("");
        dataInicio1.setDate(null);
        cboProcedInt.setSelectedIndex(0);
        cboMedicoInt.setSelectedIndex(0);
        cboLeito.setSelectedIndex(0);
        cboCID.setSelectedIndex(0);
        cboLocal.setSelectedIndex(0);                
        
        dataAlta.setDate(null);
        horaAlta.setText("");
        cboProcedAlta.setSelectedIndex(0);
        cboMedicoAlta.setSelectedIndex(0);
        cboMotivoAlta.setSelectedIndex(0);
        cboCIDAlta.setSelectedIndex(0);
    }//GEN-LAST:event_bntExcluir1ActionPerformed

    private void bntGravar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGravar1ActionPerformed
        // TODO add your handling code here:
        if(inter==null){
                    System.out.println("inter e nulo");
                    return;
                }
        Alta a = new Alta();
        paciente = new PacienteJpaController().getPaciente(txtPront.getText());
//        inter = new InternacaoJpaController().getInterPaciente(paciente.getId().toString());    
        System.out.println("passou 1");
        List ags = new InternacaoJpaController().getInternacao(paciente);
        System.out.println("passou 2");
        System.out.println(ags.toArray().toString());
        a.setMedico((Profissional)cboMedicoAlta.getSelectedItem());
        a.setHora(horaAlta.getText());
        a.setMotivo((MotivoAlta)cboMotivoAlta.getSelectedItem());
        a.setProcedimento((Procedimento)cboProcedAlta.getSelectedItem());
        a.setCid((CID)cboCIDAlta.getSelectedItem());        
        a.setDataAlta(dataAlta.getCalendar());
        a.setPaciente(paciente);
        
        a.setLocal((Localizacao)cboLocal.getSelectedItem());
        a.setLeito((Leito)cboLeito.getSelectedItem());
        //List alta = new AltaJpaController().getListAlta(paciente);
        System.out.println("passou 3");
        if ((ags.isEmpty())) {
            System.out.println("passou 4");
            try {
                System.out.println("passou 5");
                inter = new InternacaoJpaController().getInterPaciente(txtPront.getText());                
                System.out.println("passou 6");
                a.setInternacao(inter.getId().toString());
                new AltaJpaController().create(a);
                System.out.println("passou 7");
                new InternacaoJpaController().destroy(inter.getId());
                System.out.println("passou 8");
                
            } catch (NonexistentEntityException ex) {
                JOptionPane.showMessageDialog(null, "Não existe internação para este nº de Prontuário");
                txtPront.setText("");
                txtNome.setText("");
                txtCPF.setText("");
                txtDataNasc.setText("");
                txtMaeInt.setText("");
                txtTelefone.setText("");
                txtHora.setText("");
                dataInicio1.setDate(null);
                cboProcedInt.setSelectedIndex(0);
                cboMedicoInt.setSelectedIndex(0);
                cboLeito.setSelectedIndex(0);
                cboCID.setSelectedIndex(0);
                cboLocal.setSelectedIndex(0);                
        
                dataAlta.setDate(null);
                horaAlta.setText("");
                cboProcedAlta.setSelectedIndex(0);
                cboMedicoAlta.setSelectedIndex(0);
                cboMotivoAlta.setSelectedIndex(0);
                cboCIDAlta.setSelectedIndex(0);
            }
            System.out.println("passou 9");
            JOptionPane.showMessageDialog(null, "Alta realizada");
            txtPront.setText("");
        txtNome.setText("");
        txtCPF.setText("");
        txtDataNasc.setText("");
        txtMaeInt.setText("");
        txtTelefone.setText("");
        txtHora.setText("");
        dataInicio1.setDate(null);
        cboProcedInt.setSelectedIndex(0);
        cboMedicoInt.setSelectedIndex(0);
        cboLeito.setSelectedIndex(0);
        cboCID.setSelectedIndex(0);
        cboLocal.setSelectedIndex(0);                
        
        dataAlta.setDate(null);
        horaAlta.setText("");
        cboProcedAlta.setSelectedIndex(0);
        cboMedicoAlta.setSelectedIndex(0);
        cboMotivoAlta.setSelectedIndex(0);
        cboCIDAlta.setSelectedIndex(0);
        }
        
        
        System.out.println("passou 10");
        
        

    }//GEN-LAST:event_bntGravar1ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        
        List lMotivo= new MotivoAltaJpaController().findMotivoAltaEntities();
        cboMotivoAlta.removeAllItems();
        for (int i = 0; i < lMotivo.size(); i++) {
         cboMotivoAlta.addItem(lMotivo.get(i));
        }
        
        List lProced = new ProcedimentoJpaController().findProcedimentoEntities();
        cboProcedAlta.removeAllItems();
        for (int i = 0; i < lProced.size(); i++) {
         cboProcedAlta.addItem(lProced.get(i));
        }
        
        List lProced2 = new ProcedimentoJpaController().findProcedimentoEntities();
        cboProcedInt.removeAllItems();
        for (int i = 0; i < lProced2.size(); i++) {
         cboProcedInt.addItem(lProced2.get(i));
        }
        
        
        List lCid = new CIDJpaController().findCIDEntities();
        cboCID.removeAllItems();
        for (int i = 0; i < lCid.size(); i++) {
         cboCID.addItem(lCid.get(i));
        }
        
        List lCid2 = new CIDJpaController().findCIDEntities();
        cboCIDAlta.removeAllItems();
        for (int i = 0; i < lCid2.size(); i++) {
         cboCIDAlta.addItem(lCid2.get(i));
        }

        List lLocal = new LocalizacaoJpaController().findLocalizacaoEntities();
        cboLocal.removeAllItems();
        for (int i = 0; i < lLocal.size(); i++) {
         cboLocal.addItem(lLocal.get(i));
        }
        
        
        List list = new ProfissionalJpaController().findProfissionalEntities();
        cboMedicoInt.removeAllItems();
        for (int i = 0; i < list.size(); i++) {
            Profissional m = (Profissional)list.get(i);
            cboMedicoInt.addItem(m);
        }
        
        List list2 = new ProfissionalJpaController().findProfissionalEntities();
        cboMedicoAlta.removeAllItems();
        for (int i = 0; i < list2.size(); i++) {
            Profissional m = (Profissional)list2.get(i);
            cboMedicoAlta.addItem(m);
        }
        
    }//GEN-LAST:event_formInternalFrameActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar1;
    private javax.swing.JButton bntEditar1;
    private javax.swing.JButton bntExcluir1;
    private javax.swing.JButton bntGravar1;
    private javax.swing.JButton btnBuscarPaciente;
    private javax.swing.JComboBox cboCID;
    private javax.swing.JComboBox cboCIDAlta;
    private javax.swing.JComboBox cboLeito;
    private javax.swing.JComboBox cboLocal;
    private javax.swing.JComboBox cboMedicoAlta;
    private javax.swing.JComboBox cboMedicoInt;
    private javax.swing.JComboBox cboMotivoAlta;
    private javax.swing.JComboBox cboProcedAlta;
    private javax.swing.JComboBox cboProcedInt;
    private javax.swing.JComboBox cboTipo;
    private com.toedter.calendar.JDateChooser dataAlta;
    private com.toedter.calendar.JDateChooser dataInicio1;
    private javax.swing.JTextField horaAlta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtDescProcedAlta;
    private javax.swing.JTextField txtDescProcedInt;
    private javax.swing.JTextField txtDescricaoCIDAlta;
    private javax.swing.JTextField txtDescricaoCIDInt;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtMaeInt;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPront;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
