/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui2;
//Foi modicicado a preescrição
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import jpa.AgendamentoJpaController;
import jpa.CirurgiaMedicamentoJpaController;
import jpa.EspecialidadeJpaController;
import jpa.ProfissionalJpaController;
import jpa.PacienteJpaController;
import jpa.SalaJpaController;
import jpa.exceptions.NonexistentEntityException;
import model.Agendamento;
import model.Especialidade;
import model.Profissional;
import model.Paciente;
import model.Sala;

/**
 *
 * @author Manoela
 */
public class guiAgendamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form guiAgendamento
     */
    Paciente paciente;
    Agendamento ag;
    public guiAgendamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarPaciente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPront = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bntEditar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bntCancelar = new javax.swing.JButton();
        txtMae = new javax.swing.JTextField();
        bntGravar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboEspecialidade = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        cboMedico = new javax.swing.JComboBox();
        bntExcluir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cboHoraFim = new javax.swing.JComboBox();
        cboSala = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txtProcedimento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cboHoraInicio = new javax.swing.JComboBox();
        burcarAgend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPaciente = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMedicamento = new javax.swing.JList();
        dataInicio = new com.toedter.calendar.JDateChooser();
        dataFim = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Agendamento de Cirurgia");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnBuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Pesquisa.jpg"))); // NOI18N
        btnBuscarPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Prontuário:");

        txtPront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProntActionPerformed(evt);
            }
        });

        txtNome.setEditable(false);

        jLabel15.setText("Nome:");

        jLabel5.setText("Telefone:");

        txtTelefone.setEditable(false);
        txtTelefone.setEnabled(false);

        txtCPF.setEditable(false);
        txtCPF.setEnabled(false);

        jLabel2.setText("CPF:");

        txtDataNasc.setEditable(false);
        txtDataNasc.setEnabled(false);

        jLabel4.setText("Data de Nascimento:");

        bntEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Edita.jpg"))); // NOI18N
        bntEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntEditar.setMaximumSize(new java.awt.Dimension(59, 63));
        bntEditar.setMinimumSize(new java.awt.Dimension(59, 63));
        bntEditar.setPreferredSize(new java.awt.Dimension(68, 68));
        bntEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditarActionPerformed(evt);
            }
        });

        jLabel3.setText("Mãe:");

        bntCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Cancelar.jpg"))); // NOI18N
        bntCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntCancelar.setPreferredSize(new java.awt.Dimension(68, 68));
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        txtMae.setEditable(false);
        txtMae.setEnabled(false);

        bntGravar.setForeground(new java.awt.Color(153, 153, 153));
        bntGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/GRAVAR1.jpg"))); // NOI18N
        bntGravar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntGravar.setPreferredSize(new java.awt.Dimension(68, 68));
        bntGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGravarActionPerformed(evt);
            }
        });

        jLabel8.setText("Especialidade:");

        jLabel14.setText("Hora Final:");

        jLabel9.setText("Sala Cirurgica:");

        cboEspecialidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboEspecialidadeItemStateChanged(evt);
            }
        });

        jLabel13.setText("Hora Inicial:");

        cboMedico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMedicoItemStateChanged(evt);
            }
        });

        bntExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Excluir.jpg"))); // NOI18N
        bntExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntExcluir.setPreferredSize(new java.awt.Dimension(68, 68));
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        jLabel7.setText("Médico:");

        cboHoraFim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "08:00", "09:00", "10:00", "11:00", "12:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00" }));

        jLabel10.setText("Procedimento:");

        jLabel11.setText("Data Inicial:");

        jLabel12.setText("Data Final:");

        cboHoraInicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00" }));
        cboHoraInicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboHoraInicioItemStateChanged(evt);
            }
        });

        burcarAgend.setText("Buscar agendamento");
        burcarAgend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burcarAgendActionPerformed(evt);
            }
        });

        lstPaciente.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPacienteValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPaciente);

        jLabel6.setText("Procedimentos/Paciente");

        jLabel16.setText("Medicamentos");

        jScrollPane2.setViewportView(lstMedicamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(41, 41, 41)
                        .addComponent(cboMedico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addComponent(txtMae))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboSala, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(bntGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(bntEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(bntCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(bntExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGap(15, 15, 15)
                                .addComponent(dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(txtPront, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarPaciente)
                        .addGap(18, 18, 18)
                        .addComponent(burcarAgend))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProcedimento)
                            .addComponent(dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(btnBuscarPaciente))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(txtPront, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(burcarAgend)
                                .addGap(23, 23, 23)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cboEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(cboHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(cboHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed
        // TODO add your handling code here:

        try {
            paciente = new PacienteJpaController().getPaciente(txtPront.getText());
            // Procurar por nome:
            //aluno = new AlunoJpaController().getAluno(txtNome.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Paciente não encontrado");
            txtNome.setText("");
            txtCPF.setText("");
            txtDataNasc.setText("");
            txtMae.setText("");
            txtTelefone.setText("");
            txtProcedimento.setText("");
            txtPront.setText("");
            dataFim.setDate(null);
            dataInicio.setDate(null);
            cboEspecialidade.setSelectedIndex(0);
            cboHoraFim.setSelectedIndex(0);
            cboHoraInicio.setSelectedIndex(0);
            cboMedico.setSelectedIndex(0);
            cboSala.setSelectedIndex(0);
            lstPaciente.setModel(new DefaultListModel()); 
            return;
        }

        txtPront.setText(paciente.getId().toString());
        txtNome.setText(paciente.getNome().toString());
        txtCPF.setText(paciente.getCpf().toString());
        txtDataNasc.setText(paciente.getDataNasc().toString());
        txtMae.setText(paciente.getMae().toString());
        txtTelefone.setText(paciente.getTelefone().toString());

    }//GEN-LAST:event_btnBuscarPacienteActionPerformed

    private void txtProntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProntActionPerformed

    private void bntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarActionPerformed
        // TODO add your handling code here:
        ag=(Agendamento)lstPaciente.getSelectedValue();
        if (ag==null) return;

        ag.setEspecialidade((Especialidade) cboEspecialidade.getSelectedItem());
        ag.setProfissional((Profissional)cboMedico.getSelectedItem());
        ag.setHoraInicio((String) cboHoraInicio.getSelectedItem());
        ag.setHoraFim((String) cboHoraFim.getSelectedItem());
        ag.setProcedimento(txtProcedimento.getText());
        ag.setDataInicio(dataInicio.getCalendar());
        ag.setDataFim(dataFim.getCalendar());
        ag.setSala((Sala)cboSala.getSelectedItem());
                

        try {
            new AgendamentoJpaController().edit(ag);
            

        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "Paciente inexistente");
            txtPront.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Procure o Administrador do Sistema");
        }

        JOptionPane.showMessageDialog(null,"Detalhes de Agendamento Alterados");

        txtNome.setText("");
        txtCPF.setText("");
        txtDataNasc.setText("");
        txtMae.setText("");
        txtTelefone.setText("");
        txtProcedimento.setText("");
        txtPront.setText("");
        dataFim.setDate(null);
        dataInicio.setDate(null);
        cboEspecialidade.setSelectedIndex(0);
        cboHoraFim.setSelectedIndex(0);
        cboHoraInicio.setSelectedIndex(0);
        cboMedico.setSelectedIndex(0);
        cboSala.setSelectedIndex(0);
        lstPaciente.setModel(new DefaultListModel());
        lstMedicamento.setModel(new DefaultListModel());

    }//GEN-LAST:event_bntEditarActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void bntGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGravarActionPerformed
        // TODO add your handling code here:
        Agendamento a = new Agendamento();
        paciente = new PacienteJpaController().getPaciente(txtPront.getText());

            a.setEspecialidade((Especialidade) cboEspecialidade.getSelectedItem());
            a.setProfissional((Profissional)cboMedico.getSelectedItem());
            a.setHoraInicio((String) cboHoraInicio.getSelectedItem());
            a.setHoraFim((String) cboHoraFim.getSelectedItem());
            a.setProcedimento(txtProcedimento.getText());
            a.setDataInicio(dataInicio.getCalendar());
            a.setDataFim(dataFim.getCalendar());
            a.setSala((Sala)cboSala.getSelectedItem());           
            a.setPaciente(paciente);
        
     
        List ags = new AgendamentoJpaController().getListAgendamento(dataInicio.getCalendar(), (String)cboHoraInicio.getSelectedItem(), (Sala)cboSala.getSelectedItem());
        
        if (!(ags.isEmpty())) {
            JOptionPane.showMessageDialog(null, "Já existe agendamento nesta sala para a data/hora indicada");
            return;
        }

        
        new AgendamentoJpaController().create(a);
        JOptionPane.showMessageDialog(null,"Cirurgia agendada\n \tCod: "+ a.getId());
        txtNome.setText("");
        txtCPF.setText("");
        txtDataNasc.setText("");
        txtMae.setText("");
        txtTelefone.setText("");
        txtProcedimento.setText("");
        txtPront.setText("");
        dataFim.setDate(null);
        dataInicio.setDate(null);
        cboEspecialidade.setSelectedIndex(0);
        cboHoraFim.setSelectedIndex(0);
        cboHoraInicio.setSelectedIndex(0);
        cboMedico.setSelectedIndex(0);
        cboSala.setSelectedIndex(0);

    }//GEN-LAST:event_bntGravarActionPerformed

    private void cboEspecialidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboEspecialidadeItemStateChanged
        // TODO add your handling code here:
        Especialidade e = (Especialidade) cboEspecialidade.getSelectedItem();

        if(e==null) return;

        List list = new ProfissionalJpaController().getListProfissional(e);
        cboMedico.removeAllItems();
        for (int i = 0; i < list.size(); i++) {
            Profissional m = (Profissional)list.get(i);
            cboMedico.addItem(m);
        }

        List l = new SalaJpaController().getListSala(e);
        cboSala.removeAllItems();
        for (int i = 0; i < l.size(); i++) {
            Sala s = (Sala)l.get(i);
            cboSala.addItem(s);
        }
    }//GEN-LAST:event_cboEspecialidadeItemStateChanged

    private void cboMedicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMedicoItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cboMedicoItemStateChanged

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        // TODO add your handling code here:
                try {
                    ag =(Agendamento)lstPaciente.getSelectedValue();
                        new AgendamentoJpaController().destroy(ag.getId());
                        
                    } catch (NonexistentEntityException ex) {
                        JOptionPane.showMessageDialog(null, "Este agendamento não existe");
            
                    }
        
                JOptionPane.showMessageDialog(null,"Agendamento excluído!");
        
        txtNome.setText("");
        txtCPF.setText("");
        txtDataNasc.setText("");
        txtMae.setText("");
        txtTelefone.setText("");
        txtProcedimento.setText("");
        txtPront.setText("");
        dataFim.setDate(null);
        dataInicio.setDate(null);
        cboEspecialidade.setSelectedIndex(0);
        cboHoraFim.setSelectedIndex(0);
        cboHoraInicio.setSelectedIndex(0);
        cboMedico.setSelectedIndex(0);
        cboSala.setSelectedIndex(0);
        lstPaciente.setModel(new DefaultListModel()); 
        
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void cboHoraInicioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboHoraInicioItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cboHoraInicioItemStateChanged

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        List l = new EspecialidadeJpaController().findEspecialidadeEntities();
        
        cboEspecialidade.removeAllItems();
        for (int i=0;i<l.size();i++) {
        cboEspecialidade.addItem(l.get(i));
        }
        
    }//GEN-LAST:event_formInternalFrameActivated

    private void burcarAgendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burcarAgendActionPerformed
        // TODO add your handling code here:
        paciente = new PacienteJpaController().getPaciente(txtPront.getText());
            
            txtNome.setText(paciente.getNome().toString());   
            txtCPF.setText(paciente.getCpf().toString());
            txtMae.setText(paciente.getMae().toString());  
            txtDataNasc.setText(paciente.getDataNasc().toString());
            txtTelefone.setText(paciente.getTelefone().toString());
        
        try {
            List l = new AgendamentoJpaController().getAgendamentoPac(txtPront.getText());
            lstPaciente.setListData(l.toArray());
            
            if(l.isEmpty()){
            JOptionPane.showMessageDialog(null, "Não foi agendada Cirurgia com este número de prontuário");
            txtNome.setText("");
            txtCPF.setText("");
            txtDataNasc.setText("");
            txtMae.setText("");
            txtTelefone.setText("");
            txtProcedimento.setText("");
            txtPront.setText("");
            dataFim.setDate(null);
        dataInicio.setDate(null);
        cboEspecialidade.setSelectedIndex(0);
        cboHoraFim.setSelectedIndex(0);
        cboHoraInicio.setSelectedIndex(0);
        cboMedico.setSelectedIndex(0);
        cboSala.setSelectedIndex(0);
        lstPaciente.setModel(new DefaultListModel()); 
        lstMedicamento.setModel(new DefaultListModel());
                System.out.println("aqui1");
            }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi agendada Cirurgia com este número de prontuário");
        
        System.out.println("aqui 2");
        return;
        }
        
               
        
        
    }//GEN-LAST:event_burcarAgendActionPerformed

    private void lstPacienteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPacienteValueChanged
        // TODO add your handling code here:
        
        Agendamento a  = (Agendamento)lstPaciente.getSelectedValue();
        
        txtPront.setText(a.getPaciente().getId().toString());
        txtNome.setText(a.getPaciente().getNome().toString());   
        txtCPF.setText(a.getPaciente().getCpf().toString());
        txtMae.setText(a.getPaciente().getMae().toString());  
        txtDataNasc.setText(a.getPaciente().getDataNasc().toString());
        txtTelefone.setText(a.getPaciente().getTelefone().toString());
        
        cboSala.setSelectedItem(a.getSala());       
        cboEspecialidade.setSelectedItem(a.getEspecialidade());
        cboMedico.setSelectedItem(a.getProfissional());
        
        dataInicio.setCalendar(a.getDataInicio());
        dataFim.setCalendar(a.getDataFim());        
        cboHoraInicio.setSelectedItem(a.getHoraInicio());
        cboHoraFim.setSelectedItem(a.getHoraFim());
        
        txtProcedimento.setText(a.getProcedimento().toString());
        
        lstMedicamento.removeAll();
        List l = new CirurgiaMedicamentoJpaController().getMedicamentos(a.getId().toString());
        lstMedicamento.setListData(l.toArray());
        
    }//GEN-LAST:event_lstPacienteValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntEditar;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntGravar;
    private javax.swing.JButton btnBuscarPaciente;
    private javax.swing.JButton burcarAgend;
    private javax.swing.JComboBox cboEspecialidade;
    private javax.swing.JComboBox cboHoraFim;
    private javax.swing.JComboBox cboHoraInicio;
    private javax.swing.JComboBox cboMedico;
    private javax.swing.JComboBox cboSala;
    private com.toedter.calendar.JDateChooser dataFim;
    private com.toedter.calendar.JDateChooser dataInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstMedicamento;
    private javax.swing.JList lstPaciente;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtMae;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtProcedimento;
    private javax.swing.JTextField txtPront;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
