/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui2;

import java.util.List;
import javax.swing.JOptionPane;
import jpa.CIDJpaController;
import jpa.EspecialidadeJpaController;
import jpa.InternacaoJpaController;
import jpa.LeitoJpaController;
import jpa.LocalizacaoJpaController;
import jpa.ProfissionalJpaController;
import jpa.PacienteJpaController;
import jpa.ProcedimentoJpaController;
import jpa.exceptions.NonexistentEntityException;
import model.CID;
import model.Especialidade;
import model.Internacao;
import model.Leito;
import model.Localizacao;
import model.Profissional;
import model.Paciente;
import model.Procedimento;

/**
 *
 * @author Manoela
 */
public class guiInternacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form guiInternacao
     */
    Internacao inter;
    public guiInternacao() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboMedico = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cboEspecialidade = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtPront = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarPaciente = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtMae = new javax.swing.JTextField();
        burcarInt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bntExcluir1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        bntGravar1 = new javax.swing.JButton();
        bntCancelar1 = new javax.swing.JButton();
        bntEditar1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        dataInicio1 = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        cboProced = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cboLeito = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        cboCID = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtInt = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDescricaoCID = new javax.swing.JTextField();
        cboTipo = new javax.swing.JComboBox();
        cboLocal = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txtDescProced = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);
        setTitle("Internação");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        cboMedico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMedicoItemStateChanged(evt);
            }
        });

        jLabel7.setText("Médico:");

        cboEspecialidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboEspecialidadeItemStateChanged(evt);
            }
        });

        jLabel8.setText("Especialidade:");

        txtPront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProntActionPerformed(evt);
            }
        });

        jLabel1.setText("Prontuário:");

        btnBuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Pesquisa.jpg"))); // NOI18N
        btnBuscarPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteActionPerformed(evt);
            }
        });

        jLabel15.setText("Nome:");

        txtNome.setEditable(false);

        txtMae.setEditable(false);
        txtMae.setEnabled(false);

        burcarInt.setText("Buscar Internação");
        burcarInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burcarIntActionPerformed(evt);
            }
        });

        jLabel3.setText("Mãe:");

        jLabel4.setText("Data de Nascimento:");

        jLabel2.setText("CPF:");

        txtDataNasc.setEditable(false);
        txtDataNasc.setEnabled(false);

        txtTelefone.setEditable(false);
        txtTelefone.setEnabled(false);

        txtCPF.setEditable(false);
        txtCPF.setEnabled(false);

        jLabel5.setText("Telefone:");

        bntExcluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Excluir.jpg"))); // NOI18N
        bntExcluir1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntExcluir1.setPreferredSize(new java.awt.Dimension(68, 68));
        bntExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluir1ActionPerformed(evt);
            }
        });

        jLabel17.setText("Hora:");

        bntGravar1.setForeground(new java.awt.Color(153, 153, 153));
        bntGravar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/GRAVAR1.jpg"))); // NOI18N
        bntGravar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntGravar1.setPreferredSize(new java.awt.Dimension(68, 68));
        bntGravar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGravar1ActionPerformed(evt);
            }
        });

        bntCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Cancelar.jpg"))); // NOI18N
        bntCancelar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntCancelar1.setPreferredSize(new java.awt.Dimension(68, 68));
        bntCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelar1ActionPerformed(evt);
            }
        });

        bntEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Edita.jpg"))); // NOI18N
        bntEditar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntEditar1.setMaximumSize(new java.awt.Dimension(59, 63));
        bntEditar1.setMinimumSize(new java.awt.Dimension(59, 63));
        bntEditar1.setPreferredSize(new java.awt.Dimension(68, 68));
        bntEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditar1ActionPerformed(evt);
            }
        });

        jLabel18.setText("Procedimento:");

        jLabel20.setText("Data:");

        cboProced.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboProcedItemStateChanged(evt);
            }
        });

        jLabel6.setText("Leito:");

        cboLeito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLeitoItemStateChanged(evt);
            }
        });

        jLabel19.setText("CID:");

        cboCID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCIDItemStateChanged(evt);
            }
        });
        cboCID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCIDActionPerformed(evt);
            }
        });

        jLabel9.setText("Tipo:");

        jLabel21.setText("Local:");

        jLabel22.setText("Internação:");

        txtInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntActionPerformed(evt);
            }
        });

        jLabel16.setText("Descriçao:");

        txtDescricaoCID.setEditable(false);
        txtDescricaoCID.setEnabled(false);

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cirúrgico", "Clínico", "Pediátrico", "Obstétrico" }));
        cboTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTipoItemStateChanged(evt);
            }
        });

        cboLocal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLocalItemStateChanged(evt);
            }
        });

        jLabel10.setText("Descrição:");

        txtDescProced.setEditable(false);
        txtDescProced.setEnabled(false);
        txtDescProced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescProcedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboProced, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDescProced, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPront, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtInt)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(burcarInt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBuscarPaciente)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dataInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHora))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txtNome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefone))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMae, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboCID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDescricaoCID))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDataNasc)
                                        .addGap(116, 116, 116))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cboEspecialidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cboMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cboLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cboLeito, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(bntGravar1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(bntEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(bntCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(bntExcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(burcarInt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscarPaciente)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPront, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cboEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cboProced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtDescProced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboLeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel9)
                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtDescricaoCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntGravar1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntExcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboMedicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMedicoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicoItemStateChanged

    private void cboEspecialidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboEspecialidadeItemStateChanged
        // TODO add your handling code here:
        Especialidade e = (Especialidade) cboEspecialidade.getSelectedItem();

        if(e==null) return;

        List list = new ProfissionalJpaController().getListProfissional(e);
        cboMedico.removeAllItems();
        for (int i = 0; i < list.size(); i++) {
            Profissional p = (Profissional)list.get(i);
            cboMedico.addItem(p);
        }
        
    }//GEN-LAST:event_cboEspecialidadeItemStateChanged

    private void txtProntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProntActionPerformed

    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed
        // TODO add your handling code here:
        Paciente paciente;
        try {
            paciente = new PacienteJpaController().getPaciente(txtPront.getText());
            // Procurar por nome:
            //aluno = new AlunoJpaController().getAluno(txtNome.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Paciente com este número de prontuário não encontrado");
            txtNome.setText("");
            txtCPF.setText("");
            txtDataNasc.setText("");
            txtMae.setText("");
            txtTelefone.setText("");
            txtHora.setText("");
            txtPront.setText("");
            dataInicio1.setDate(null);
            cboEspecialidade.setSelectedIndex(0);
            cboLeito.setSelectedIndex(0);
            cboProced.setSelectedIndex(0);
            cboMedico.setSelectedIndex(0);
            return;
        }

        txtPront.setText(paciente.getId().toString());
        txtNome.setText(paciente.getNome().toString());
        txtCPF.setText(paciente.getCpf().toString());
        txtDataNasc.setText(paciente.getDataNasc().toString());
        txtMae.setText(paciente.getMae().toString());
        txtTelefone.setText(paciente.getTelefone().toString());
        txtInt.setText("");       
        txtHora.setText("");        
        dataInicio1.setDate(null);
        cboEspecialidade.setSelectedIndex(0);
        cboProced.setSelectedIndex(0);
        cboMedico.setSelectedIndex(0);
        cboLocal.setSelectedIndex(0);
        cboLeito.setSelectedIndex(0);
        cboCID.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnBuscarPacienteActionPerformed

    private void burcarIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burcarIntActionPerformed
        // TODO add your handling code here:
        
        try {
            inter = new InternacaoJpaController().getInter(txtInt.getText());
            // Procurar por nome:
            //aluno = new AlunoJpaController().getAluno(txtNome.getText());
            txtPront.setText(inter.getProntuario().toString());
            txtNome.setText(inter.getNome().toString());
            txtMae.setText(inter.getMae().toString());
            txtCPF.setText(inter.getCpf().toString());
            txtDataNasc.setText(inter.getDataNasc().toString());
            txtTelefone.setText(inter.getTelefone().toString());
            cboEspecialidade.setSelectedItem(inter.getEspecialidade());
            cboMedico.setSelectedItem(inter.getMedico());
            dataInicio1.setCalendar(inter.getDataEntrada());
            txtHora.setText(inter.getHora().toString());
            cboLeito.setSelectedItem(inter.getLeito());
            cboLocal.setSelectedItem(inter.getLocal());
            cboTipo.setSelectedItem(inter.getTipoInter().toString());            
            cboProced.setSelectedItem(inter.getProced());
            cboCID.setSelectedItem(inter.getCid());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi encontrada Internação com este código");
            txtInt.setText("");
            txtNome.setText("");
            txtCPF.setText("");
            txtDataNasc.setText("");
            txtMae.setText("");
            txtTelefone.setText("");
            txtHora.setText("");
            txtPront.setText("");
            dataInicio1.setDate(null);
            cboEspecialidade.setSelectedIndex(0);
            cboProced.setSelectedIndex(0);
            cboMedico.setSelectedIndex(0);
            cboLeito.setSelectedIndex(0);
            cboCID.setSelectedIndex(0);
        }

    }//GEN-LAST:event_burcarIntActionPerformed

    private void bntExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluir1ActionPerformed
        // TODO add your handling code here:
        try {
            new InternacaoJpaController().destroy(inter.getId());
        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "Internação não existe");

        }

        JOptionPane.showMessageDialog(null,"Internação de cód. "+ inter.getId()+ " excluída");

            txtInt.setText("");
            txtNome.setText("");
            txtCPF.setText("");
            txtDataNasc.setText("");
            txtMae.setText("");
            txtTelefone.setText("");
            txtHora.setText("");
            txtPront.setText("");
            dataInicio1.setDate(null);
            cboEspecialidade.setSelectedIndex(0);
            cboProced.setSelectedIndex(0);
            cboMedico.setSelectedIndex(0);
            cboLeito.setSelectedIndex(0);
            cboCID.setSelectedIndex(0);
        
    }//GEN-LAST:event_bntExcluir1ActionPerformed

    private void bntGravar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGravar1ActionPerformed
        // TODO add your handling code here:
        Internacao a = new Internacao();

        a.setEspecialidade((Especialidade) cboEspecialidade.getSelectedItem());
        a.setMedico((Profissional)cboMedico.getSelectedItem());
        a.setHora(txtHora.getText());        
        a.setProced((Procedimento)cboProced.getSelectedItem());
        a.setCid((CID)cboCID.getSelectedItem());
        a.setLeito((Leito)cboLeito.getSelectedItem());
        a.setDataEntrada(dataInicio1.getCalendar());
        a.setProntuario(txtPront.getText());
        a.setMae(txtMae.getText());
        a.setNome(txtNome.getText());
        a.setTelefone(txtTelefone.getText());
        a.setCpf(txtCPF.getText());
        a.setDataNasc(txtDataNasc.getText());
        a.setTipoInter((String)cboTipo.getSelectedItem());
        a.setLocal((Localizacao)cboLocal.getSelectedItem());
        
        List in = new InternacaoJpaController().getPaciente(txtPront.toString());
        if (!(in.isEmpty())) {
            JOptionPane.showMessageDialog(null, "Já foi efetuada internação para este nº de prontuário");            
            return;
        }
        
        List ags = new InternacaoJpaController().getListInternacao((Leito)cboLeito.getSelectedItem());

        if (!(ags.isEmpty())) {
            JOptionPane.showMessageDialog(null, "Leito ocupado");            
            return;
        }

        new InternacaoJpaController().create(a);
        JOptionPane.showMessageDialog(null,"Internação efetuada\n \tCod: "+ a.getId());
            txtInt.setText("");
            txtNome.setText("");
            txtCPF.setText("");
            txtDataNasc.setText("");
            txtMae.setText("");
            txtTelefone.setText("");
            txtHora.setText("");
            txtPront.setText("");
            dataInicio1.setDate(null);
            cboEspecialidade.setSelectedIndex(0);
            cboProced.setSelectedIndex(0);
            cboMedico.setSelectedIndex(0);
            cboLeito.setSelectedIndex(0);
            cboCID.setSelectedIndex(0);
            cboLocal.setSelectedIndex(0);
            cboTipo.setSelectedIndex(0);
    }//GEN-LAST:event_bntGravar1ActionPerformed

    private void bntCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelar1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bntCancelar1ActionPerformed

    private void bntEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditar1ActionPerformed
        // TODO add your handling code here:

         
        if (inter==null) return;

        inter.setEspecialidade((Especialidade) cboEspecialidade.getSelectedItem());
        inter.setMedico((Profissional)cboMedico.getSelectedItem());
        inter.setLeito((Leito) cboLeito.getSelectedItem());
        inter.setCid((CID)cboCID.getSelectedItem());
        inter.setProced((Procedimento)cboProced.getSelectedItem());
        inter.setDataEntrada(dataInicio1.getCalendar());
        inter.setHora(txtHora.getText());

        try {
            new InternacaoJpaController().edit(inter);

        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "erro");
            txtPront.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Procure o Administrador do Sistema");
        }

        JOptionPane.showMessageDialog(null,"Detalhes de Internação Alterados");
            txtInt.setText("");
            txtNome.setText("");
            txtCPF.setText("");
            txtDataNasc.setText("");
            txtMae.setText("");
            txtTelefone.setText("");
            txtHora.setText("");
            txtPront.setText("");
            dataInicio1.setDate(null);
            cboEspecialidade.setSelectedIndex(0);
            cboProced.setSelectedIndex(0);
            cboMedico.setSelectedIndex(0);
            cboLeito.setSelectedIndex(0);
            cboCID.setSelectedIndex(0);
            cboLocal.setSelectedIndex(0);
            cboTipo.setSelectedIndex(0);
        
    
    }//GEN-LAST:event_bntEditar1ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        List l = new EspecialidadeJpaController().findEspecialidadeEntities();
        cboEspecialidade.removeAllItems();
        for (int i=0;i<l.size();i++) {
        cboEspecialidade.addItem(l.get(i));
        }
        
        
        
        List lCid = new CIDJpaController().findCIDEntities();
        cboCID.removeAllItems();
        for (int i = 0; i < lCid.size(); i++) {
         cboCID.addItem(lCid.get(i));
        }

        List lLocal = new LocalizacaoJpaController().findLocalizacaoEntities();
        cboLocal.removeAllItems();
        for (int i = 0; i < lLocal.size(); i++) {
         cboLocal.addItem(lLocal.get(i));
        }
          
        
        txtPront.grabFocus();
    }//GEN-LAST:event_formInternalFrameActivated

    private void cboCIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCIDItemStateChanged
        // TODO add your handling code here:
        
         CID c = (CID) cboCID.getSelectedItem();

        if(c==null) return;
        txtDescricaoCID.setText(c.getDescricao().toString());
        
    }//GEN-LAST:event_cboCIDItemStateChanged

    private void cboLeitoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLeitoItemStateChanged
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cboLeitoItemStateChanged

    private void cboLocalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLocalItemStateChanged
        // TODO add your handling code here:
        
        Localizacao e = (Localizacao) cboLocal.getSelectedItem();
        String s = (String) cboTipo.getSelectedItem();

        if(e==null) return;
        
        List l = new LeitoJpaController().getLeitoLocal(e,s);                
        cboLeito.removeAllItems();
        for (int i = 0; i < l.size(); i++) {   
         Leito ti = (Leito)l.get(i);
          cboLeito.addItem(ti);
        }

//        List list = new TipoLeitoJpaController().getListTipo(e);
//        cboTipo.removeAllItems();
//        for (int i = 0; i < list.size(); i++) {
//        TipoLeito ti = (TipoLeito)list.get(i);
//            cboTipo.addItem(ti);            
//        }
        
       
        
        
    }//GEN-LAST:event_cboLocalItemStateChanged

    private void txtDescProcedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescProcedActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtDescProcedActionPerformed

    private void cboProcedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboProcedItemStateChanged
        // TODO add your handling code here:
        Procedimento p = (Procedimento) cboProced.getSelectedItem();

        if(p==null) return;
        txtDescProced.setText(p.getDescricao().toString());
    }//GEN-LAST:event_cboProcedItemStateChanged

    private void cboTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTipoItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboTipoItemStateChanged

    private void cboCIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCIDActionPerformed

    private void txtIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar1;
    private javax.swing.JButton bntEditar1;
    private javax.swing.JButton bntExcluir1;
    private javax.swing.JButton bntGravar1;
    private javax.swing.JButton btnBuscarPaciente;
    private javax.swing.JButton burcarInt;
    private javax.swing.JComboBox cboCID;
    private javax.swing.JComboBox cboEspecialidade;
    private javax.swing.JComboBox cboLeito;
    private javax.swing.JComboBox cboLocal;
    private javax.swing.JComboBox cboMedico;
    private javax.swing.JComboBox cboProced;
    private javax.swing.JComboBox cboTipo;
    private com.toedter.calendar.JDateChooser dataInicio1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtDescProced;
    private javax.swing.JTextField txtDescricaoCID;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtInt;
    private javax.swing.JTextField txtMae;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPront;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
