/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui2;

import com.sun.istack.internal.logging.Logger;
import gui.Tabela;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import jpa.LeitoJpaController;
import jpa.LocalizacaoJpaController;
import jpa.TipoLeitoJpaController;
import model.Leito;
import model.Localizacao;
import model.TipoLeito;

/**
 *
 * @author Manoela
 */
public class guiLeito extends javax.swing.JInternalFrame {

    /**
     * Creates new form guiLeito
     */
    public guiLeito() {
        initComponents();
        //preencherTabela("Select l.id from Leito l");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox();
        cboLocal = new javax.swing.JComboBox();
        bntGravar = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Leito");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel2.setText("Tipo de Leito:");

        jLabel3.setText("Localização:");

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cirúrgico", "Clínico", "Pediátrico", "Obstétrico" }));
        cboTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTipoItemStateChanged(evt);
            }
        });

        cboLocal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLocalItemStateChanged(evt);
            }
        });

        bntGravar.setForeground(new java.awt.Color(153, 153, 153));
        bntGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/GRAVAR1.jpg"))); // NOI18N
        bntGravar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntGravar.setPreferredSize(new java.awt.Dimension(68, 68));
        bntGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGravarActionPerformed(evt);
            }
        });

        bntCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Cancelar.jpg"))); // NOI18N
        bntCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntCancelar.setPreferredSize(new java.awt.Dimension(68, 68));
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(bntGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bntCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboLocal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bntCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

////    public void preencherTabela(String SQL){
////        ArrayList dados = new ArrayList();
////        String[] coluna = new String[]{"Cód. Leito", "Nº Sala", "Tipo", "Localização"};
////        new LeitoJpaController().executaSQL(SQL);
////        //new LeitoJpaController().getLeito();
////        try{
////            new LeitoJpaController().rs.first();
////            do{
////                dados.add(new Object[]{new LeitoJpaController().rs.getLong("id"), new LeitoJpaController().rs.getString("localizacao"), new LeitoJpaController().rs.getString("numero"), new LeitoJpaController().rs.getString("tipo")});                
////              }while(new LeitoJpaController().rs.next());
////        }catch(SQLException ex){
////           JOptionPane.showMessageDialog(null, "Erro");            
////        }
////        
////          Tabela tab = new Tabela(dados, coluna);    
////          tableLeito.setModel(tab);
////          tableLeito.getColumnModel().getColumn(0).setPreferredWidth(80);
////          tableLeito.getColumnModel().getColumn(0).setResizable(false);
////          tableLeito.getColumnModel().getColumn(1).setPreferredWidth(180);
////          tableLeito.getColumnModel().getColumn(1).setResizable(false);
////          tableLeito.getColumnModel().getColumn(2).setPreferredWidth(80);
////          tableLeito.getColumnModel().getColumn(2).setResizable(false);
////          tableLeito.getColumnModel().getColumn(3).setPreferredWidth(180);
////          tableLeito.getColumnModel().getColumn(3).setResizable(false);
////          tableLeito.getTableHeader().setReorderingAllowed(false);
////          //tableLeito.getAutoResizeMode(tableLeito.AUTO_RESIZE_OFF);
////          tableLeito.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
////          
////    }
    private void bntGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGravarActionPerformed
        Leito le = new Leito();
        le.setLocalizacao((Localizacao) cboLocal.getSelectedItem());
        le.setTipo((String) cboTipo.getSelectedItem());
        

        new LeitoJpaController().create(le);

        JOptionPane.showMessageDialog(null,"Leito cadastrado: \t" + le.getId());
        
//        tableLeito.removeAll();
//        List l = new LeitoJpaController().getLeito();
        //tableLeito.setListData(l.toArray());

        
    }//GEN-LAST:event_bntGravarActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        
       // List l = new LeitoJpaController().getLeito();
        //lstMotivoAlta.list();
                
      //  tableLeito.setListData(l.toArray());
//        List l2 = new TipoLeitoJpaController().findTipoLeitoEntities();
//        
//        cboTipo.removeAllItems();
//        for (int i=0;i<l2.size();i++) {
//        cboTipo.addItem(l2.get(i));
//        }
        
       List l = new LocalizacaoJpaController().findLocalizacaoEntities();
        
        cboLocal.removeAllItems();
        for (int i=0;i<l.size();i++) {
        cboLocal.addItem(l.get(i));
        }
        
        
        
    }//GEN-LAST:event_formInternalFrameActivated

    private void cboTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTipoItemStateChanged
        // TODO add your handling code here:
//         TipoLeito e = (TipoLeito) cboTipo.getSelectedItem();
//
//        if(e==null) return;
//
//        List l = new LocalizacaoJpaController().getListLocal(e);
//        
//        cboLocal.removeAllItems();
//        for (int i=0;i<l.size();i++) {
//        cboLocal.addItem(l.get(i));
//        }
    }//GEN-LAST:event_cboTipoItemStateChanged

    private void cboLocalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLocalItemStateChanged
       
//         Localizacao e = (Localizacao) cboLocal.getSelectedItem();
//
//        if(e==null) return;
//
//        List list = new TipoLeitoJpaController().getListTipo(e);
//        cboTipo.removeAllItems();
//        for (int i = 0; i < list.size(); i++) {
//        TipoLeito ti = (TipoLeito)list.get(i);
//            cboTipo.addItem(ti);            
//        }
    }//GEN-LAST:event_cboLocalItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntGravar;
    private javax.swing.JComboBox cboLocal;
    private javax.swing.JComboBox cboTipo;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
