/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui2;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import jpa.AgendamentoJpaController;
import jpa.CirurgiaMedicamentoJpaController;
import jpa.MedicamentoJpaController;
import jpa.PacienteJpaController;
import model.Agendamento;
import model.CirurgiaMedicamento;
import model.Medicamento;
import model.Paciente;

/**
 *
 * @author Manoela
 */
public class guiMediCirurgia extends javax.swing.JInternalFrame {

    /**
     * Creates new form guiMediCirurgia
     */
    Paciente paciente;
    Agendamento ag;
    public guiMediCirurgia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPront = new javax.swing.JTextField();
        burcarAgend = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPaciente = new javax.swing.JList();
        txtNome = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cboMedicamentos = new javax.swing.JComboBox();
        bntAdicionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMedicamento = new javax.swing.JList();
        txtCirurgia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDataCirurgia = new com.toedter.calendar.JDateChooser();
        txtPeriodo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Adicionar Medicamento em Cirurgia");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Prontuário:");

        txtPront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProntActionPerformed(evt);
            }
        });

        burcarAgend.setText("Buscar agendamento");
        burcarAgend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burcarAgendActionPerformed(evt);
            }
        });

        jLabel6.setText("Cirurgias do Paciente:");

        lstPaciente.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPacienteValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPaciente);

        txtNome.setEditable(false);

        jLabel16.setText("Medicamentos para Cirurgia:");

        bntAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Adicionar.jpg"))); // NOI18N
        bntAdicionar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicionarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstMedicamento);

        txtCirurgia.setEditable(false);

        jLabel2.setText("Data da Cirurgia:");

        txtDataCirurgia.setEnabled(false);

        jLabel3.setText("h");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCirurgia)
                            .addComponent(txtDataCirurgia, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPront, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(burcarAgend, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPront, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(burcarAgend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDataCirurgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtCirurgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(bntAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProntActionPerformed

    private void burcarAgendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burcarAgendActionPerformed
        // TODO add your handling code here:
        paciente = new PacienteJpaController().getPaciente(txtPront.getText());

        txtNome.setText(paciente.getNome().toString());

        try {
            List l = new AgendamentoJpaController().getAgendamentoPac(txtPront.getText());
            lstPaciente.setListData(l.toArray());

            if(l.isEmpty()){
                JOptionPane.showMessageDialog(null, "Não foi agendada Cirurgia com este número de prontuário");
                txtNome.setText("");
                txtPront.setText("");    
                txtDataCirurgia.setDate(null);
                txtCirurgia.setText("");
            lstPaciente.setModel(new DefaultListModel());
            lstMedicamento.setModel(new DefaultListModel());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi agendada Cirurgia com este número de prontuário");
            txtNome.setText("");
            txtPront.setText("");
            txtDataCirurgia.setDate(null);
            txtCirurgia.setText("");
            lstPaciente.setModel(new DefaultListModel());
            lstMedicamento.setModel(new DefaultListModel());
        }

    }//GEN-LAST:event_burcarAgendActionPerformed

    private void lstPacienteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPacienteValueChanged
        // TODO add your handling code here:

        Agendamento a  = (Agendamento)lstPaciente.getSelectedValue();

        txtPront.setText(a.getPaciente().getId().toString());
        txtNome.setText(a.getPaciente().getNome().toString());
        txtDataCirurgia.setDate(a.getDataInicio().getTime());
        txtCirurgia.setText(a.getProcedimento().toString());

        lstMedicamento.removeAll();
        List l = new CirurgiaMedicamentoJpaController().getMedicamentos(a.getId().toString());
        lstMedicamento.setListData(l.toArray());

    }//GEN-LAST:event_lstPacienteValueChanged

    private void bntAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionarActionPerformed

        CirurgiaMedicamento cm = new CirurgiaMedicamento();
        ag =(Agendamento)lstPaciente.getSelectedValue();

        cm.setAgendamento(ag);
        cm.setDataCirurgia(txtDataCirurgia.getCalendar());
        cm.setMedicamento((Medicamento)cboMedicamentos.getSelectedItem());
        cm.setPeriodo(txtPeriodo.getText());

        new CirurgiaMedicamentoJpaController().create(cm);
        JOptionPane.showMessageDialog(null,"Novo Medicamento adicionado a Cirurgia '"+ ag.getProcedimento()+"'\nPaciente: " +ag.getPaciente().getNome().toString());
        lstMedicamento.removeAll();
        List l = new CirurgiaMedicamentoJpaController().getMedicamentos(ag.getId().toString());
        lstMedicamento.setListData(l.toArray());
        //lstMedicamento.setModel(new DefaultListModel());

    }//GEN-LAST:event_bntAdicionarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        List l2 = new MedicamentoJpaController().findMedicamentoEntities();
        
        cboMedicamentos.removeAllItems();
        for (int i=0;i<l2.size();i++) {
        cboMedicamentos.addItem(l2.get(i));
        }
    }//GEN-LAST:event_formInternalFrameActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdicionar;
    private javax.swing.JButton burcarAgend;
    private javax.swing.JComboBox cboMedicamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstMedicamento;
    private javax.swing.JList lstPaciente;
    private javax.swing.JTextField txtCirurgia;
    private com.toedter.calendar.JDateChooser txtDataCirurgia;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPeriodo;
    private javax.swing.JTextField txtPront;
    // End of variables declaration//GEN-END:variables
}
