/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui2;

import java.util.List;
import javax.swing.JOptionPane;
import jpa.BairroJpaController;
import jpa.CidadeJpaController;
import jpa.EstadoJpaController;
import jpa.PacienteJpaController;
import jpa.exceptions.NonexistentEntityException;
import model.Bairro;
import model.Cidade;
import model.Estado;
import model.Paciente;

/**
 *
 * @author Manoela
 */
public class guiPaciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form guiPaciente
     */
    Paciente paciente;
    
    public guiPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        cboEstado = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cboBairro = new javax.swing.JComboBox();
        cboCidade = new javax.swing.JComboBox();
        txtNome = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codProntuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bntExcluir = new javax.swing.JButton();
        txtDataNasc = new javax.swing.JFormattedTextField();
        rdaFeminino = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();
        rdaMasculino = new javax.swing.JRadioButton();
        bntEditar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        bntGravar = new javax.swing.JButton();
        txtNumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRg = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPai = new javax.swing.JTextField();
        txtMae = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtComp = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCertidao = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro Paciente");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        cboEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboEstadoItemStateChanged(evt);
            }
        });

        jLabel11.setText("Bairro:");

        cboCidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCidadeItemStateChanged(evt);
            }
        });

        jLabel13.setText("Nº:");

        jLabel12.setText("Nome:");

        jLabel4.setText("Comp.:");

        jLabel3.setText("Logradouro:");

        jLabel2.setText("Endereço:");

        codProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codProntuarioActionPerformed(evt);
            }
        });

        jLabel1.setText("PRONTUÁRIO:");

        jLabel16.setText("Telefone:");

        bntExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Excluir.jpg"))); // NOI18N
        bntExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntExcluir.setPreferredSize(new java.awt.Dimension(68, 68));
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        try {
            txtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        bgSexo.add(rdaFeminino);
        rdaFeminino.setText("Feminino");
        rdaFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdaFemininoActionPerformed(evt);
            }
        });

        jLabel17.setText("Sexo:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        bntCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Cancelar.jpg"))); // NOI18N
        bntCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntCancelar.setPreferredSize(new java.awt.Dimension(68, 68));
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        bgSexo.add(rdaMasculino);
        rdaMasculino.setText("Masculino");
        rdaMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdaMasculinoActionPerformed(evt);
            }
        });

        bntEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Edita.jpg"))); // NOI18N
        bntEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntEditar.setMaximumSize(new java.awt.Dimension(59, 63));
        bntEditar.setMinimumSize(new java.awt.Dimension(59, 63));
        bntEditar.setPreferredSize(new java.awt.Dimension(68, 68));
        bntEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditarActionPerformed(evt);
            }
        });

        jLabel14.setText("Data de Nascimento:");

        jLabel5.setText("Cidade:");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        bntGravar.setForeground(new java.awt.Color(153, 153, 153));
        bntGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/GRAVAR1.jpg"))); // NOI18N
        bntGravar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntGravar.setPreferredSize(new java.awt.Dimension(68, 68));
        bntGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGravarActionPerformed(evt);
            }
        });

        jLabel7.setText("CEP:");

        jLabel6.setText("Estado:");

        jLabel9.setText("RG:");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setText("CPF:");

        jLabel10.setText("Filiação:");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setName(""); // NOI18N

        jLabel15.setText("Certidão:");

        jLabel18.setText("       Pai");

        jLabel19.setText("      Mãe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel12)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(codProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                        .addComponent(btnBuscar)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(rdaFeminino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rdaMasculino)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                            .addComponent(txtRg, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                            .addComponent(txtCertidao))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPai, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                            .addComponent(txtMae)))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRua)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtComp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(bntGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(bntEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(bntCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(bntExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(codProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(rdaFeminino)
                            .addComponent(rdaMasculino)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtCertidao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cboCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cboBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bntEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addComponent(bntCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntGravar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bntExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboEstadoItemStateChanged
        // TODO add your handling code here:
        Estado e = (Estado) cboEstado.getSelectedItem();

        if(e==null) return;
        List l = new CidadeJpaController().getListCidadeEstado(e);
        cboCidade.removeAllItems();
        for (int i = 0; i < l.size(); i++) {
            Cidade c = (Cidade)l.get(i);
            cboCidade.addItem(c);
        }
    }//GEN-LAST:event_cboEstadoItemStateChanged

    private void cboCidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCidadeItemStateChanged
        // TODO add your handling code here:
        Cidade c = (Cidade) cboCidade.getSelectedItem();

        if(c==null) return;
        List l = new BairroJpaController().getListCidadeBairro(c);
        cboBairro.removeAllItems();
        for (int i = 0; i < l.size(); i++) {
            Bairro b = (Bairro)l.get(i);
            cboBairro.addItem(b);
        }
    }//GEN-LAST:event_cboCidadeItemStateChanged

    private void codProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codProntuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codProntuarioActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        // TODO add your handling code here:
        try {
            new PacienteJpaController().destroy(paciente.getId());
        } catch (NonexistentEntityException ex) {
            //JOptionPane.showMessageDialog(null, "Medico não existente");

        }

        JOptionPane.showMessageDialog(null,"Dados de Paciente Excluídos");

        codProntuario.setText("");
        txtCpf.setText("");
        txtNumero.setText("");
        txtRua.setText("");
        txtNome.setText("");
        txtTelefone.setText("");
        txtDataNasc.setText("");
        txtRg.setText("");
        txtCertidao.setText("");
        txtPai.setText("");
        txtMae.setText("");
        txtCep.setText("");
        txtComp.setText("");
        cboBairro.setSelectedIndex(0);
        cboCidade.setSelectedIndex(0);
        cboEstado.setSelectedIndex(0);
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void rdaFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdaFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdaFemininoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        try {
            paciente = new PacienteJpaController().getPaciente(codProntuario.getText());
            // Procurar por nome:
            //aluno = new AlunoJpaController().getAluno(txtNome.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Paciente não encontrado");
            codProntuario.setText("");
            txtCpf.setText("");
            txtNumero.setText("");
            txtRua.setText("");
            txtNome.setText("");
            txtTelefone.setText("");
            txtDataNasc.setText("");
            txtRg.setText("");
            txtCertidao.setText("");
            txtPai.setText("");
            txtMae.setText("");
            txtCep.setText("");
            txtComp.setText("");
            cboBairro.setSelectedIndex(0);
            cboCidade.setSelectedIndex(0);
            cboEstado.setSelectedIndex(0);
            return;
        }

        codProntuario.setText(paciente.getId().toString());
        txtNome.setText(paciente.getNome().toString());
        txtCpf.setText(paciente.getCpf().toString());
        txtRg.setText(paciente.getIdentidade().toString());
        txtDataNasc.setText(paciente.getDataNasc().toString());
        txtNumero.setText(paciente.getNumero().toString());
        txtRua.setText(paciente.getRua().toString());
        txtTelefone.setText(paciente.getTelefone().toString());
        txtCep.setText(paciente.getCep().toString());
        txtPai.setText(paciente.getPai().toString());
        txtMae.setText(paciente.getMae().toString());
        txtCertidao.setText(paciente.getCertidao().toString());
        txtComp.setText(paciente.getComplemento().toString());
        setaSexo(paciente.getSexo());
        
        cboEstado.setSelectedItem(paciente.getBairro().getCidade().getEstado());
        cboCidade.setSelectedItem(paciente.getBairro().getCidade());
        cboBairro.setSelectedItem(paciente.getBairro());

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void rdaMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdaMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdaMasculinoActionPerformed

    private void bntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarActionPerformed
        // TODO add your handling code here:
        if (paciente==null) return;

        paciente.setBairro((Bairro) cboBairro.getSelectedItem());
        paciente.setRua(txtRua.getText());
        paciente.setCpf(txtCpf.getText());
        paciente.setNome(txtNome.getText());
        paciente.setNumero(txtNumero.getText());
        paciente.setTelefone(txtTelefone.getText());
        paciente.setDataNasc(txtDataNasc.getText());
        paciente.setIdentidade(txtRg.getText());
        paciente.setCertidao(txtCertidao.getText());
        paciente.setPai(txtPai.getText());
        paciente.setMae(txtMae.getText());
        paciente.setCep(txtCep.getText());
        paciente.setComplemento(txtComp.getText());
        paciente.setSexo(escolheSexo());

        try {
            new PacienteJpaController().edit(paciente);

        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "Paciente inexistente");
            codProntuario.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Procure o Administrador do Sistema");
        }

        JOptionPane.showMessageDialog(null,"Dados de Paciente Alterados");

        codProntuario.setText("");
        txtCpf.setText("");
        txtNumero.setText("");
        txtRua.setText("");
        txtNome.setText("");
        txtTelefone.setText("");
        txtDataNasc.setText("");
        txtRg.setText("");
        txtCertidao.setText("");
        txtPai.setText("");
        txtMae.setText("");
        txtCep.setText("");
        txtComp.setText("");
        cboBairro.setSelectedIndex(0);
        cboCidade.setSelectedIndex(0);
        cboEstado.setSelectedIndex(0);
    }//GEN-LAST:event_bntEditarActionPerformed

    private void bntGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGravarActionPerformed
        // TODO add your handling code here:
        Paciente m = new Paciente();

        m.setNome(txtNome.getText());
        m.setCpf(txtCpf.getText());
        m.setCep(txtCep.getText());
        m.setDataNasc(txtDataNasc.getText());
        m.setIdentidade(txtRg.getText());
        m.setNumero(txtNumero.getText());
        m.setRua(txtRua.getText());
        m.setTelefone(txtTelefone.getText());
        m.setBairro((Bairro) cboBairro.getSelectedItem());
        m.setPai(txtPai.getText());
        m.setMae(txtMae.getText());
        m.setCertidao(txtCertidao.getText());
        m.setComplemento(txtComp.getText());
        m.setSexo(escolheSexo()); 

        new PacienteJpaController().create(m);

        JOptionPane.showMessageDialog(null,"Paciente cadastrado\n \tID: " + m.getId());
        codProntuario.setText("");
        txtCpf.setText("");
        txtNumero.setText("");
        txtRua.setText("");
        txtNome.setText("");
        txtTelefone.setText("");
        txtDataNasc.setText("");
        txtRg.setText("");
        txtCertidao.setText("");
        txtPai.setText("");
        txtMae.setText("");
        txtCep.setText("");
        txtComp.setText("");
        cboBairro.setSelectedIndex(0);
        cboCidade.setSelectedIndex(0);
        cboEstado.setSelectedIndex(0);;
        txtNome.grabFocus();

    }//GEN-LAST:event_bntGravarActionPerformed

    public String escolheSexo() {

        if (rdaMasculino.isSelected()) {

        return "M";

        } else {

        return "F";

        }

    }

    public  void setaSexo(String sexo) {
        sexo=paciente.getSexo();
        
        if (String.valueOf(sexo).equals("M")) {
//        if (String.valueOf(paciente./*get(paciente.getSelectedRow())*/.getSexo()).equals("M"))
        rdaMasculino.setSelected(true);

        } else {

        rdaFeminino.setSelected(true);

        }

    }
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        txtDataNasc.grabFocus();        
        
        List l2 = new EstadoJpaController().findEstadoEntities();
        
        cboEstado.removeAllItems();
        for (int i=0;i<l2.size();i++) {
        cboEstado.addItem(l2.get(i));
        }
    }//GEN-LAST:event_formInternalFrameActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntEditar;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntGravar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox cboBairro;
    private javax.swing.JComboBox cboCidade;
    private javax.swing.JComboBox cboEstado;
    private javax.swing.JTextField codProntuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rdaFeminino;
    private javax.swing.JRadioButton rdaMasculino;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCertidao;
    private javax.swing.JTextField txtComp;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataNasc;
    private javax.swing.JTextField txtMae;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPai;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JTextField txtRua;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
