/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui2;

import gui.Tabela;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import jpa.InternacaoJpaController;
import jpa.MedicamentoJpaController;
import jpa.PacienteJpaController;
import jpa.PrescricaoJpaController;
import jpa.ProcedimentoJpaController;
import jpa.ProfissionalJpaController;
import jpa.exceptions.NonexistentEntityException;
import model.Internacao;
import model.Medicamento;
import model.Profissional;
import model.Paciente;
import model.Prescricao;
import model.Procedimento;

/**
 *
 * @author Ciça
 */
public class guiPrecriscao extends javax.swing.JInternalFrame {
    private Internacao inter;

    /**
     * Creates new form guiPrecriscao
     */
    public guiPrecriscao() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        burcarInt = new javax.swing.JButton();
        txtInt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMedic = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cboMedico = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cboProcedimento = new javax.swing.JComboBox();
        txtPront = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnBuscarPaciente = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        dataInicio1 = new com.toedter.calendar.JDateChooser();
        bntGravar1 = new javax.swing.JButton();
        txtHora = new javax.swing.JTextField();
        bntExcluir1 = new javax.swing.JButton();
        cboMedicamento = new javax.swing.JComboBox();
        txtNome = new javax.swing.JTextField();
        bntCancelar1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProced = new javax.swing.JTable();
        bntEditar1 = new javax.swing.JButton();
        txtLocal = new javax.swing.JTextField();
        txtLeito = new javax.swing.JTextField();
        bntAdicMedicamento = new javax.swing.JButton();
        cboPeriodo1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cboPeriodo2 = new javax.swing.JComboBox();
        bntAdicionarProced = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel6.setText("Leito:");

        burcarInt.setText("Buscar Internação");
        burcarInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burcarIntActionPerformed(evt);
            }
        });

        jLabel22.setText("Internação:");

        tableMedic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableMedic);

        jLabel4.setText("Assinatura:");

        cboMedico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMedicoItemStateChanged(evt);
            }
        });

        jLabel7.setText("Médico:");

        txtPront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProntActionPerformed(evt);
            }
        });

        jLabel1.setText("Prontuário:");

        jLabel20.setText("Data:");

        btnBuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Pesquisa.jpg"))); // NOI18N
        btnBuscarPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteActionPerformed(evt);
            }
        });

        jLabel17.setText("Hora:");

        bntGravar1.setForeground(new java.awt.Color(153, 153, 153));
        bntGravar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Gravar.jpg"))); // NOI18N
        bntGravar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntGravar1.setPreferredSize(new java.awt.Dimension(68, 68));
        bntGravar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGravar1ActionPerformed(evt);
            }
        });

        bntExcluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Excluir.jpg"))); // NOI18N
        bntExcluir1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntExcluir1.setPreferredSize(new java.awt.Dimension(68, 68));
        bntExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluir1ActionPerformed(evt);
            }
        });

        cboMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMedicamentoActionPerformed(evt);
            }
        });

        txtNome.setEditable(false);

        bntCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Cancelar.jpg"))); // NOI18N
        bntCancelar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntCancelar1.setPreferredSize(new java.awt.Dimension(68, 68));
        bntCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelar1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Nome:");

        jLabel21.setText("Local:");

        jLabel2.setText("Medicamentos:");

        jLabel3.setText("Procedimentos:");

        tableProced.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableProced);

        bntEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Editar.jpg"))); // NOI18N
        bntEditar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntEditar1.setMaximumSize(new java.awt.Dimension(59, 63));
        bntEditar1.setMinimumSize(new java.awt.Dimension(59, 63));
        bntEditar1.setPreferredSize(new java.awt.Dimension(68, 68));
        bntEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditar1ActionPerformed(evt);
            }
        });

        txtLocal.setEditable(false);

        txtLeito.setEditable(false);

        bntAdicMedicamento.setText("Adicionar");
        bntAdicMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicMedicamentoActionPerformed(evt);
            }
        });

        cboPeriodo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2/2", "4/4", "6/6", "8/8", "12/12", "24/24" }));

        jLabel5.setText("Período:");

        cboPeriodo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2/2", "4/4", "6/6", "8/8", "12/12", "24/24" }));

        bntAdicionarProced.setText("Adicionar");
        bntAdicionarProced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicionarProcedActionPerformed(evt);
            }
        });

        jLabel8.setText("Período:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLeito))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPront, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtInt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBuscarPaciente)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dataInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(burcarInt)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(bntGravar1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(bntEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(bntCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(bntExcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboPeriodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bntAdicMedicamento))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cboPeriodo2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173)
                        .addComponent(bntAdicionarProced))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel7)
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(cboMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(burcarInt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscarPaciente)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPront, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel21)
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPeriodo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(bntAdicMedicamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPeriodo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(bntAdicionarProced))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cboMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntGravar1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntExcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void burcarIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burcarIntActionPerformed
        // TODO add your handling code here:

        try {
            inter = new InternacaoJpaController().getInter(txtInt.getText());
            // Procurar por nome:
            //aluno = new AlunoJpaController().getAluno(txtNome.getText());
            txtPront.setText(inter.getProntuario().toString());
            txtNome.setText(inter.getNome().toString());
            cboMedicamento.setSelectedItem(inter.getMedico());
            dataInicio1.setCalendar(inter.getDataEntrada());
            txtHora.setText(inter.getHora().toString());
            txtLeito.setText(inter.getLeito().toString());
            txtLocal.setText(inter.getLocal().toString());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi encontrada Internação com este código");
//            txtInt.setText("");
//            txtNome.setText("");
//            txtHora.setText("");
//            txtPront.setText("");
//            dataInicio1.setDate(null);
//            cboMedicamento.setSelectedIndex(0);

        }
    }//GEN-LAST:event_burcarIntActionPerformed

    private void cboMedicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMedicoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicoItemStateChanged

    private void txtProntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProntActionPerformed

    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed
        // TODO add your handling code here:
        Paciente paciente;
        try {
            paciente = new PacienteJpaController().getPaciente(txtPront.getText());
            // Procurar por nome:
            //aluno = new AlunoJpaController().getAluno(txtNome.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Paciente com este número de prontuário não encontrado");
//            txtNome.setText("");
//            txtHora.setText("");
//            txtPront.setText("");
//            dataInicio1.setDate(null);
//            cboMedicamento.setSelectedIndex(0);
            return;
        }

        txtPront.setText(paciente.getId().toString());
        txtNome.setText(paciente.getNome().toString());
//        txtInt.setText("");
//        txtHora.setText("");
        dataInicio1.setDate(null);
        cboMedicamento.setSelectedIndex(0);
    }//GEN-LAST:event_btnBuscarPacienteActionPerformed

    private void bntGravar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGravar1ActionPerformed
        // TODO add your handling code here:
        Internacao a = new Internacao();

        a.setMedico((Profissional)cboMedico.getSelectedItem());
        a.setHora(txtHora.getText());
        a.setProced((Procedimento)cboProcedimento.getSelectedItem());
        a.setDataEntrada(dataInicio1.getCalendar());
        a.setProntuario(txtPront.getText());
        a.setNome(txtNome.getText());


        new InternacaoJpaController().create(a);
        JOptionPane.showMessageDialog(null,"Prescrição efetuada\n \tCod: "+ a.getId());
////        txtInt.setText("");
////        txtNome.setText("");
////        txtHora.setText("");
////        txtPront.setText("");
////        dataInicio1.setDate(null);
////        cboProcedimento.setSelectedIndex(0);
////        cboMedico.setSelectedIndex(0);
//        
    }//GEN-LAST:event_bntGravar1ActionPerformed

    private void bntExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluir1ActionPerformed
        // TODO add your handling code here:
        try {
            new InternacaoJpaController().destroy(inter.getId());
        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "Precrição não existe");

        }

        JOptionPane.showMessageDialog(null,"Prescrição de cód. "+ inter.getId()+ " excluída");

        txtInt.setText("");
        txtNome.setText("");
        txtHora.setText("");
        txtPront.setText("");
        dataInicio1.setDate(null);
        cboProcedimento.setSelectedIndex(0);
        cboMedico.setSelectedIndex(0);
    

    }//GEN-LAST:event_bntExcluir1ActionPerformed

    private void bntCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelar1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bntCancelar1ActionPerformed

    private void bntEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditar1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_bntEditar1ActionPerformed

    private void bntAdicMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicMedicamentoActionPerformed
        // TODO add your handling code here:
        Prescricao p = new Prescricao();
        inter = new InternacaoJpaController().getInter(txtInt.getText());
        
        p.setMedico((Profissional)cboMedico.getSelectedItem());
        p.setHora(txtHora.getText());        
        p.setMedicamento((Medicamento)cboMedicamento.getSelectedItem());
        p.setDataPresc(dataInicio1.getCalendar());
        p.setInternacao(inter);
        p.setPeriodoMedicamento((cboPeriodo1.getSelectedItem()).toString());

        
        new PrescricaoJpaController().create(p);
        
        JOptionPane.showMessageDialog(null,"Prescrição efetuada\n \tCod: "+ p.getId());
        
        List l = new PrescricaoJpaController().getListPresMed(dataInicio1, inter, p);
        preencherTabelaMedicamento(l);

            
    }//GEN-LAST:event_bntAdicMedicamentoActionPerformed

public void preencherTabelaMedicamento(List list) {       

        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Descrição", "Período" };   
        Object[] linha;
        try{
          if(list.isEmpty()){
                       JOptionPane.showMessageDialog(rootPane, "Prescrição Médica não existe \nnesta data!");

                   }

                   for(int i = 0; i<list.size(); i++){
                   linha = new Object[2];
                   System.out.println(i);
                   linha[0]=((Prescricao)list.get(i)).getMedicamento();
                   linha[1]=((Prescricao)list.get(i)).getPeriodoMedicamento();
                   dados.add(linha);  
                   System.out.println("dentro do for"+linha);

               }

        }catch(OutOfMemoryError oe){
            JOptionPane.showMessageDialog(null, "JAVA HEAP SPACE!"+oe);
        }catch(ArrayIndexOutOfBoundsException ae){
            JOptionPane.showMessageDialog(null, "ArrayIndexOutOfBoundsException: 1"+ae);
        }catch(NullPointerException ne){
             JOptionPane.showMessageDialog(null, "vazio");
        }

        Tabela tab = new Tabela(dados, Colunas);

        tableMedic.setModel(tab);
        tableMedic.getColumnModel().getColumn(0).setPreferredWidth(363);
        tableMedic.getColumnModel().getColumn(0).setResizable(false);
        tableMedic.getColumnModel().getColumn(1).setPreferredWidth(100);
        tableMedic.getColumnModel().getColumn(1).setResizable(false);
        tableMedic.getTableHeader().setReorderingAllowed(false);
        tableMedic.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tableMedic.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
    
public void preencherTabelaProcedimento(List list) {       

        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Descrição", "Período" };   
        Object[] linha;
        try{
          if(list.isEmpty()){
                       JOptionPane.showMessageDialog(rootPane, "Prescrição Médica não existe \nnesta data!");

                   }

                   for(int i = 0; i<list.size(); i++){
                   linha = new Object[2];
                   System.out.println(i);
                   linha[0]=((Prescricao)list.get(i)).getProcedimento();
                   linha[1]=((Prescricao)list.get(i)).getPeriodoProced();
                   dados.add(linha);  
                   System.out.println("dentro do for"+linha);

               }

        }catch(OutOfMemoryError oe){
            JOptionPane.showMessageDialog(null, "JAVA HEAP SPACE!"+oe);
        }catch(ArrayIndexOutOfBoundsException ae){
            JOptionPane.showMessageDialog(null, "ArrayIndexOutOfBoundsException: 1"+ae);
        }catch(NullPointerException ne){
             JOptionPane.showMessageDialog(null, "vazio");
        }

        Tabela tab = new Tabela(dados, Colunas);

        tableProced.setModel(tab);
        tableProced.getColumnModel().getColumn(0).setPreferredWidth(363);
        tableProced.getColumnModel().getColumn(0).setResizable(false);
        tableProced.getColumnModel().getColumn(1).setPreferredWidth(100);
        tableProced.getColumnModel().getColumn(1).setResizable(false);
        tableProced.getTableHeader().setReorderingAllowed(false);
        tableProced.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tableProced.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
    private void bntAdicionarProcedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionarProcedActionPerformed
        // TODO add your handling code here:
        
         Prescricao p = new Prescricao();
        inter = new InternacaoJpaController().getInter(txtInt.getText());
        
        p.setMedico((Profissional)cboMedico.getSelectedItem());
        p.setHora(txtHora.getText());        
        p.setProcedimento((Procedimento)cboProcedimento.getSelectedItem());
        p.setDataPresc(dataInicio1.getCalendar());
        p.setInternacao(inter);
        p.setPeriodoProced((cboPeriodo2.getSelectedItem()).toString());
        
                new PrescricaoJpaController().create(p);
        
        JOptionPane.showMessageDialog(null,"Prescrição efetuada\n \tCod: "+ p.getId());
        List l = new PrescricaoJpaController().getListPresProc(dataInicio1, inter, p);
        preencherTabelaProcedimento(l);
    }//GEN-LAST:event_bntAdicionarProcedActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        List lProced = new ProcedimentoJpaController().findProcedimentoEntities();
        cboProcedimento.removeAllItems();
        for (int i = 0; i < lProced.size(); i++) {
         cboProcedimento.addItem(lProced.get(i));
        }
        List lMedic = new MedicamentoJpaController().findMedicamentoEntities();
        cboMedicamento.removeAllItems();
        for (int i = 0; i < lMedic.size(); i++) {
         cboMedicamento.addItem(lMedic.get(i));
        }
          List lMedico = new ProfissionalJpaController().findProfissionalEntities();
        cboMedico.removeAllItems();
        for (int i = 0; i < lMedico.size(); i++) {
         cboMedico.addItem(lMedico.get(i));
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void cboMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamentoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdicMedicamento;
    private javax.swing.JButton bntAdicionarProced;
    private javax.swing.JButton bntCancelar1;
    private javax.swing.JButton bntEditar1;
    private javax.swing.JButton bntExcluir1;
    private javax.swing.JButton bntGravar1;
    private javax.swing.JButton btnBuscarPaciente;
    private javax.swing.JButton burcarInt;
    private javax.swing.JComboBox cboMedicamento;
    private javax.swing.JComboBox cboMedico;
    private javax.swing.JComboBox cboPeriodo1;
    private javax.swing.JComboBox cboPeriodo2;
    private javax.swing.JComboBox cboProcedimento;
    private com.toedter.calendar.JDateChooser dataInicio1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableMedic;
    private javax.swing.JTable tableProced;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtInt;
    private javax.swing.JTextField txtLeito;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPront;
    // End of variables declaration//GEN-END:variables
}
