/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui2;

import java.util.List;
import javax.persistence.NoResultException;
import javax.swing.JOptionPane;
import jpa.AgendamentoJpaController;
import jpa.AltaJpaController;
import jpa.CirurgiaMedicamentoJpaController;
import jpa.EvolucaoJpaController;
import jpa.InternacaoJpaController;
import jpa.MaterialJpaController;
import jpa.PacienteJpaController;
import jpa.PrescricaoJpaController;
import model.Alta;
import model.Internacao;
import model.Paciente;

/**
 *
 * @author Ciça
 */
public class guiProntuarioVirtual extends javax.swing.JInternalFrame {

        Paciente paciente;
        
    /**
     * Creates new form guiProntuarioVirtual
     */
    public guiProntuarioVirtual() {
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abaCadastro = new javax.swing.JTabbedPane();
        jPanelCadastro = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtPront = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMae = new javax.swing.JTextField();
        jPanelCirurgia = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstCirurgias = new javax.swing.JList();
        jPanelEvolução = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        lstEvolucao = new javax.swing.JList();
        jPanelMadMed = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        lstMedicamento = new javax.swing.JList();
        jScrollPane11 = new javax.swing.JScrollPane();
        lstMaterial = new javax.swing.JList();
        jLabel22 = new javax.swing.JLabel();
        jPanelInternaçãoAlta = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        dataInicio1 = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtDescricaoCID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        dataAlta = new com.toedter.calendar.JDateChooser();
        jLabel26 = new javax.swing.JLabel();
        horaAlta = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtMotivoAlta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMedicoAlta = new javax.swing.JTextField();
        txtDescricaoCIDAlta2 = new javax.swing.JTextField();
        txtMedico = new javax.swing.JTextField();
        txtInt = new javax.swing.JTextField();
        txtHoraInicio1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Prontuário Virtual");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtPront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProntActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("PRONTUÁRIO:");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("Cadastro:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Nome:");

        txtNome.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("CPF:");

        txtCPF.setEditable(false);
        txtCPF.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Telefone:");

        txtTelefone.setEditable(false);
        txtTelefone.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Data de Nascimento:");

        txtDataNasc.setEditable(false);
        txtDataNasc.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mãe:");

        txtMae.setEditable(false);
        txtMae.setEnabled(false);

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addComponent(jLabel44)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPront, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addGap(265, 265, 265))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txtNome))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefone))
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMae, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataNasc)
                                .addGap(116, 116, 116)))
                        .addContainerGap())))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPront, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel44)
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(17, 17, 17)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        abaCadastro.addTab("Cadastro", jPanelCadastro);

        jLabel42.setText("Cirurgias:");

        jScrollPane7.setViewportView(lstCirurgias);

        javax.swing.GroupLayout jPanelCirurgiaLayout = new javax.swing.GroupLayout(jPanelCirurgia);
        jPanelCirurgia.setLayout(jPanelCirurgiaLayout);
        jPanelCirurgiaLayout.setHorizontalGroup(
            jPanelCirurgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCirurgiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCirurgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCirurgiaLayout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(0, 441, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCirurgiaLayout.setVerticalGroup(
            jPanelCirurgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCirurgiaLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        abaCadastro.addTab("Cirurgias", jPanelCirurgia);
        jPanelCirurgia.getAccessibleContext().setAccessibleDescription("Cirurgias");

        jLabel20.setText("Evoluções:");

        jScrollPane9.setViewportView(lstEvolucao);

        javax.swing.GroupLayout jPanelEvoluçãoLayout = new javax.swing.GroupLayout(jPanelEvolução);
        jPanelEvolução.setLayout(jPanelEvoluçãoLayout);
        jPanelEvoluçãoLayout.setHorizontalGroup(
            jPanelEvoluçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEvoluçãoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEvoluçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEvoluçãoLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 435, Short.MAX_VALUE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelEvoluçãoLayout.setVerticalGroup(
            jPanelEvoluçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEvoluçãoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 216, Short.MAX_VALUE))
        );

        abaCadastro.addTab("Evolução", jPanelEvolução);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Medicamentos:");

        jScrollPane10.setViewportView(lstMedicamento);

        jScrollPane11.setViewportView(lstMaterial);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Materiais:");

        javax.swing.GroupLayout jPanelMadMedLayout = new javax.swing.GroupLayout(jPanelMadMed);
        jPanelMadMed.setLayout(jPanelMadMedLayout);
        jPanelMadMedLayout.setHorizontalGroup(
            jPanelMadMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMadMedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMadMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addGroup(jPanelMadMedLayout.createSequentialGroup()
                        .addGroup(jPanelMadMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelMadMedLayout.setVerticalGroup(
            jPanelMadMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMadMedLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        abaCadastro.addTab("Mat. e  Med.", jPanelMadMed);

        jLabel23.setText("Internação:");

        dataInicio1.setEnabled(false);

        jLabel24.setText("Data:");

        jLabel17.setText("Hora:");

        jLabel7.setText("Médico:");

        jLabel19.setText("CID:");

        txtDescricaoCID.setEditable(false);
        txtDescricaoCID.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("INTERNAÇÃO");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("ALTA DA INTERNAÇÃO");

        jLabel25.setText("Data:");

        dataAlta.setEnabled(false);

        jLabel26.setText("Hora:");

        horaAlta.setEditable(false);

        jLabel27.setText("CID:");

        txtMotivoAlta.setEditable(false);
        txtMotivoAlta.setEnabled(false);

        jLabel11.setText("Médico:");

        jLabel9.setText("Motivo da Alta:");

        txtMedicoAlta.setEditable(false);
        txtMedicoAlta.setEnabled(false);

        txtDescricaoCIDAlta2.setEditable(false);
        txtDescricaoCIDAlta2.setEnabled(false);

        txtMedico.setEditable(false);
        txtMedico.setEnabled(false);

        txtInt.setEditable(false);
        txtInt.setEnabled(false);
        txtInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntActionPerformed(evt);
            }
        });

        txtHoraInicio1.setEditable(false);
        txtHoraInicio1.setEnabled(false);
        txtHoraInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraInicio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInternaçãoAltaLayout = new javax.swing.GroupLayout(jPanelInternaçãoAlta);
        jPanelInternaçãoAlta.setLayout(jPanelInternaçãoAltaLayout);
        jPanelInternaçãoAltaLayout.setHorizontalGroup(
            jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInternaçãoAltaLayout.createSequentialGroup()
                .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanelInternaçãoAltaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInternaçãoAltaLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(30, 30, 30)
                                .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelInternaçãoAltaLayout.createSequentialGroup()
                                .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel19))
                                .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelInternaçãoAltaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtInt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dataInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHoraInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelInternaçãoAltaLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(txtDescricaoCID, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 66, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(jPanelInternaçãoAltaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInternaçãoAltaLayout.createSequentialGroup()
                        .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11))
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDescricaoCIDAlta2, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(txtMotivoAlta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMedicoAlta, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanelInternaçãoAltaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(horaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInternaçãoAltaLayout.setVerticalGroup(
            jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInternaçãoAltaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(txtInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtHoraInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel24))
                .addGap(14, 14, 14)
                .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(txtDescricaoCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(horaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(dataAlta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMotivoAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMedicoAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanelInternaçãoAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricaoCIDAlta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        abaCadastro.addTab("Internação/Alta", jPanelInternaçãoAlta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abaCadastro)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abaCadastro, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
     
        try {
            paciente = new PacienteJpaController().getPaciente(txtPront.getText());
            // Procurar por nome:
            //aluno = new AlunoJpaController().getAluno(txtNome.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Paciente com este número de prontuário não encontrado");
            txtNome.setText("");
            txtCPF.setText("");
            txtDataNasc.setText("");
            txtMae.setText("");
            txtTelefone.setText("");
           
            return;
        }

      
        txtNome.setText(paciente.getNome().toString());
        txtCPF.setText(paciente.getCpf().toString());
        txtDataNasc.setText(paciente.getDataNasc().toString());
        txtMae.setText(paciente.getMae().toString());
        txtTelefone.setText(paciente.getTelefone().toString());
       
        lstCirurgias.removeAll();
        List l = new AgendamentoJpaController().getAgendamentoPac(txtPront.getText());
        lstCirurgias.setListData(l.toArray());
        
        lstMedicamento.removeAll();
        List l1 = new CirurgiaMedicamentoJpaController().getMedicamentos(paciente.getId().toString());
        lstMedicamento.setListData(l1.toArray());
        
        lstMaterial.removeAll();
        List l2= new MaterialJpaController().getMaterial(); //(paciente.getId().toString());
        lstMaterial.setListData(l2.toArray());
        
        lstEvolucao.removeAll();
        List l3= new EvolucaoJpaController().getListEvolucao(paciente);
        lstEvolucao.setListData(l3.toArray());
        
        Internacao inter;
         //List l4 = new InternacaoJpaController().getInternacao(paciente);
        try{
        
            inter = new InternacaoJpaController().getInterPaciente(txtPront.getText());
            txtInt.setText(inter.getProntuario().toString());
            dataInicio1.setCalendar(inter.getDataEntrada());                
            txtMedico.setText(inter.getMedico().toString());
            txtDescricaoCID.setText(inter.getCid().toString());
            txtHoraInicio1.setText(inter.getHora().toString());
            
        }catch(NoResultException e){
            txtDescricaoCID.setText("NÃO HÁ INTERNAÇÃO PARA ESTE PACIENTE");
            return;
            
        }
       
            
        
        
        Alta alta;
        try{
        
            alta = new AltaJpaController().getAlta(paciente);
            
        }catch(NoResultException e){
            txtMotivoAlta.setText("PACIENTE SE ENCONTRA INTERNADO");
            return;
            
        }
        
        
        txtDescricaoCIDAlta2.setText(alta.getCid().toString());
        dataAlta.setCalendar(alta.getDataAlta());
        horaAlta.setText(alta.getHora().toString());
        txtMedicoAlta.setText(alta.getMedico().toString());
        txtMotivoAlta.setText(alta.getMotivo().toString());
        
        
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtProntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProntActionPerformed

    private void txtIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntActionPerformed

    private void txtHoraInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraInicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraInicio1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abaCadastro;
    private javax.swing.JButton btnBuscar;
    private com.toedter.calendar.JDateChooser dataAlta;
    private com.toedter.calendar.JDateChooser dataInicio1;
    private javax.swing.JTextField horaAlta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelCirurgia;
    private javax.swing.JPanel jPanelEvolução;
    private javax.swing.JPanel jPanelInternaçãoAlta;
    private javax.swing.JPanel jPanelMadMed;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList lstCirurgias;
    private javax.swing.JList lstEvolucao;
    private javax.swing.JList lstMaterial;
    private javax.swing.JList lstMedicamento;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtDescricaoCID;
    private javax.swing.JTextField txtDescricaoCIDAlta2;
    private javax.swing.JTextField txtHoraInicio1;
    private javax.swing.JTextField txtInt;
    private javax.swing.JTextField txtMae;
    private javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtMedicoAlta;
    private javax.swing.JTextField txtMotivoAlta;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPront;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
